### Construction of ESG weight - Alternative dependent variable
* This notebook contains all the steps in constructing the dependent varibale esg_weight using monthly stock price data from CRSP.

<br>

* ESG weight - a companyâ€™s market capitalization that is held by ESG mutual funds in a given
month, divided by the total market capitalization held by ESG mutual funds in the same month.
___

In [1]:
import pandas as pd

In [2]:
msci = pd.read_stata('final_table_trimmed_for_outliers_msci.dta')

In [7]:
msci

,ID,year_month,cusip,nbr_shares,ISIN,asset_name,company_rating,industry_adjusted_score,MthPrc,MthCap,ShrOut,esg_grade_num,esg_ownership,esg_ownership_percent,treatment_date,up_or_down,upgrade_dummy,downgrade_dummy,treatment_date_up,treatment_date_down
0,1,2013-12-01,00101J10,257774,US00101J1060,ADT CORP,BBB,4.4,40.4700,"8,165,389.08",201764,4,0.001278,0.127760,NaT,,0,0,2016-04-01,NaT
1,2,2013-12-01,00105510,568705,US0010551028,AFLAC INC,BBB,4.3,66.8000,"31,134,812.00",466090,4,0.001220,0.122016,NaT,,0,0,2019-09-01,2016-11-01
2,3,2013-12-01,00108410,228380,US0010841023,AGCO CORP,BBB,5.2,59.1900,"5,762,738.40",97360,4,0.002346,0.234573,NaT,,0,0,NaT,2018-05-01
3,6,2013-12-01,00130H10,215396,US00130H1059,AES CORP,BB,3.1,14.5100,"10,482,633.42",722442,3,0.000298,0.029815,NaT,,0,0,2015-09-01,2020-12-01
4,7,2013-12-01,00206R10,2934933,US00206R1023,AT&T INC,BB,4.1,35.1600,"185,222,880.00",5268000,3,0.000557,0.055712,NaT,,0,0,2018-03-01,2017-03-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50820,905,2020-12-01,N3167Y10,44563,NL0011585146,FERRARI NV,BBB,4.5,229.5200,"42,403,360.96",184748,4,0.000241,0.024121,NaT,,0,0,2019-06-01,NaT
50821,907,2020-12-01,N5374510,179540,NL0009434992,LYONDELLBASELL INDUSTRIES NV,BBB,4.6,91.6600,"30,607,015.54",333919,4,0.000538,0.053768,NaT,,0,0,2016-11-01,NaT
50822,908,2020-12-01,N6596X10,910995,NL0009538784,NXP SEMICONDUCTORS NV,BB,4.2,159.0100,"44,598,329.75",280475,3,0.003248,0.324804,NaT,,0,0,NaT,NaT
50823,909,2020-12-01,N7248212,17068,NL0012169213,QIAGEN NV,A,6.0,52.8500,"12,089,384.65",228749,5,0.000075,0.007461,NaT,,0,0,NaT,NaT
50824,910,2020-12-01,V7780T10,460429,LR0008862868,ROYAL CARIBBEAN GROUP,BB,4.0,74.6900,"16,755,879.91",224339,3,0.002052,0.205238,NaT,,0,0,2016-09-01,2015-10-01

### Export monthly price data and holdings to calculate monthly cap held by funds for each firm
* Done on excel due to computer memory issues

In [4]:
msci[['cusip', 'nbr_shares', 'MthPrc', 'MthCap']].to_excel('esg_weight_calculation_input.xlsx', index=False)

### Read in the calculated values from excel

In [8]:
esg_weight_calculation_inputs = pd.read_excel('esg_weight_calculation_input.xlsx')

In [9]:
esg_weight_calculation_inputs

          cusip  nbr_shares    MthPrc          MthCap    m_cap_held
0      00101J10      257774   40.4700    8,165,389.08  1.043211e+07
1      00105510      568705   66.8000   31,134,812.00  3.798949e+07
2      00108410      228380   59.1900    5,762,738.40  1.351781e+07
3      00130H10      215396   14.5100   10,482,633.42  3.125396e+06
4      00206R10     2934933   35.1600  185,222,880.00  1.031922e+08
...         ...         ...       ...             ...           ...
50820  N3167Y10       44563  229.5200   42,403,360.96  1.022810e+07
50821  N5374510      179540   91.6600   30,607,015.54  1.645664e+07
50822  N6596X10      910995  159.0100   44,598,329.75  1.448573e+08
50823  N7248212       17068   52.8500   12,089,384.65  9.020438e+05
50824  V7780T10      460429   74.6900   16,755,879.91  3.438944e+07

[50825 rows x 5 columns]

In [10]:
mcap_held = esg_weight_calculation_inputs['m_cap_held']

In [11]:
final_table = pd.concat([msci, mcap_held], axis=1)

In [12]:
final_table

,ID,year_month,cusip,nbr_shares,ISIN,asset_name,company_rating,industry_adjusted_score,MthPrc,MthCap,...,esg_grade_num,esg_ownership,esg_ownership_percent,treatment_date,up_or_down,upgrade_dummy,downgrade_dummy,treatment_date_up,treatment_date_down,m_cap_held
0,1,2013-12-01,00101J10,257774,US00101J1060,ADT CORP,BBB,4.4,40.4700,"8,165,389.08",...,4,0.001278,0.127760,NaT,,0,0,2016-04-01,NaT,1.043211e+07
1,2,2013-12-01,00105510,568705,US0010551028,AFLAC INC,BBB,4.3,66.8000,"31,134,812.00",...,4,0.001220,0.122016,NaT,,0,0,2019-09-01,2016-11-01,3.798949e+07
2,3,2013-12-01,00108410,228380,US0010841023,AGCO CORP,BBB,5.2,59.1900,"5,762,738.40",...,4,0.002346,0.234573,NaT,,0,0,NaT,2018-05-01,1.351781e+07
3,6,2013-12-01,00130H10,215396,US00130H1059,AES CORP,BB,3.1,14.5100,"10,482,633.42",...,3,0.000298,0.029815,NaT,,0,0,2015-09-01,2020-12-01,3.125396e+06
4,7,2013-12-01,00206R10,2934933,US00206R1023,AT&T INC,BB,4.1,35.1600,"185,222,880.00",...,3,0.000557,0.055712,NaT,,0,0,2018-03-01,2017-03-01,1.031922e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50820,905,2020-12-01,N3167Y10,44563,NL0011585146,FERRARI NV,BBB,4.5,229.5200,"42,403,360.96",...,4,0.000241,0.024121,NaT,,0,0,2019-06-01,NaT,1.022810e+07
50821,907,2020-12-01,N5374510,179540,NL0009434992,LYONDELLBASELL INDUSTRIES NV,BBB,4.6,91.6600,"30,607,015.54",...,4,0.000538,0.053768,NaT,,0,0,2016-11-01,NaT,1.645664e+07
50822,908,2020-12-01,N6596X10,910995,NL0009538784,NXP SEMICONDUCTORS NV,BB,4.2,159.0100,"44,598,329.75",...,3,0.003248,0.324804,NaT,,0,0,NaT,NaT,1.448573e+08
50823,909,2020-12-01,N7248212,17068,NL0012169213,QIAGEN NV,A,6.0,52.8500,"12,089,384.65",...,5,0.000075,0.007461,NaT,,0,0,NaT,NaT,9.020438e+05
50824,910,2020-12-01,V7780T10,460429,LR0008862868,ROYAL CARIBBEAN GROUP,BB,4.0,74.6900,"16,755,879.91",...,3,0.002052,0.205238,NaT,,0,0,2016-09-01,2015-10-01,3.438944e+07

### Sum up monthly caps to get the total monthly cap held by all the funds in a given month.

In [13]:
tot_mcap_held = final_table.groupby('year_month')['m_cap_held'].sum().to_frame('total_mcap_held').reset_index()

In [14]:
final_table = final_table.merge(tot_mcap_held, on='year_month', validate='m:1')

### ESG weight

In [15]:
final_table['esg_weight'] = final_table['m_cap_held']/final_table['total_mcap_held']

In [16]:
final_table['esg_weight_percent'] = final_table['esg_weight']*100

In [17]:
final_table.to_stata('final_table_trimmed_for_outliers_msci_with_price_data.dta', write_index=False, convert_dates={'year_month':'tm', 'treatment_date':'tm', 'treatment_date_up':'tm', 'treatment_date_down':'tm'})

In [19]:
final_table.loc[:, ['year_month', 'm_cap_held', 'total_mcap_held', 'esg_weight', 'esg_weight_percent']]

,year_month,m_cap_held,total_mcap_held,esg_weight,esg_weight_percent
0,2013-12-01,1.043211e+07,1.692579e+10,0.000616,0.061634
1,2013-12-01,3.798949e+07,1.692579e+10,0.002244,0.224447
2,2013-12-01,1.351781e+07,1.692579e+10,0.000799,0.079865
3,2013-12-01,3.125396e+06,1.692579e+10,0.000185,0.018465
4,2013-12-01,1.031922e+08,1.692579e+10,0.006097,0.609675
...,...,...,...,...,...
50820,2020-12-01,1.022810e+07,7.496711e+10,0.000136,0.013643
50821,2020-12-01,1.645664e+07,7.496711e+10,0.000220,0.021952
50822,2020-12-01,1.448573e+08,7.496711e+10,0.001932,0.193228
50823,2020-12-01,9.020438e+05,7.496711e+10,0.000012,0.001203
50824,2020-12-01,3.438944e+07,7.496711e+10,0.000459,0.045873

In [20]:
final_table.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,50825.0,4.422450e+02,2.619620e+02,1.000000e+00,2.110000e+02,4.430000e+02,6.670000e+02,9.110000e+02
nbr_shares,50825.0,5.041767e+05,9.786325e+05,2.700000e+01,6.092000e+04,1.807840e+05,5.082140e+05,2.916940e+07
industry_adjusted_score,50825.0,4.821493e+00,2.176214e+00,0.000000e+00,3.200000e+00,4.700000e+00,6.400000e+00,1.000000e+01
ShrOut,50825.0,5.488957e+05,9.439731e+05,3.590000e+03,1.424560e+05,2.729850e+05,5.318630e+05,1.710254e+07
esg_grade_num,50825.0,3.844427e+00,1.455130e+00,1.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00,7.000000e+00
esg_ownership,50825.0,1.049251e-03,1.113258e-03,3.616714e-06,3.022859e-04,6.923830e-04,1.379099e-03,6.782155e-03
esg_ownership_percent,50825.0,1.049251e-01,1.113258e-01,3.616714e-04,3.022859e-02,6.923830e-02,1.379099e-01,6.782155e-01
upgrade_dummy,50825.0,9.227742e-03,9.561784e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
downgrade_dummy,50825.0,6.138711e-03,7.810984e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
m_cap_held,50825.0,4.080116e+07,1.085777e+08,7.204980e+03,4.035924e+06,1.229167e+07,3.691315e+07,4.901751e+09
total_mcap_held,50825.0,2.496396e+10,1.408828e+10,9.942694e+09,1.411808e+10,2.054378e+10,3.141666e+10,7.496711e+10
esg_weight,50825.0,1.672405e-03,3.303795e-03,1.247945e-07,1.919380e-04,5.745704e-04,1.638925e-03,6.996178e-02
esg_weight_percent,50825.0,1.672405e-01,3.303795e-01,1.247945e-05,1.919380e-02,5.745704e-02,1.638925e-01,6.996178e+00

In [21]:
final_table[['esg_ownership', 'esg_ownership_percent','esg_weight', 'esg_weight_percent', 'industry_adjusted_score']].describe().T

,count,mean,std,min,25%,50%,75%,max
esg_ownership,50825.0,0.001049,0.001113,3.616714e-06,0.000302,0.000692,0.001379,0.006782
esg_ownership_percent,50825.0,0.104925,0.111326,3.616714e-04,0.030229,0.069238,0.137910,0.678215
esg_weight,50825.0,0.001672,0.003304,1.247945e-07,0.000192,0.000575,0.001639,0.069962
esg_weight_percent,50825.0,0.167241,0.330380,1.247945e-05,0.019194,0.057457,0.163892,6.996178
industry_adjusted_score,50825.0,4.821493,2.176214,0.000000e+00,3.200000,4.700000,6.400000,10.000000